language: rust
rust:
    - nightly
    - beta
    - stable

cache: cargo

script:
    - cargo build --verbose $FEATURES
    - cargo test --verbose $FEATURES --no-fail-fast

notifications:
    email: false
